// import type { Metadata } from "next";
import { Poppins, Playfair_Display } from 'next/font/google'
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Head from 'next/head';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// export const metadata: Metadata = {
//   title: "Bigstep Technologies",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.variable}
      >
        <Head>
          {/* Default Meta Tags */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Bigstep Technologies" />
          <meta name="robots" content="index, follow" />
          
          {/* Open Graph Meta Tags (For Social Media Preview) */}
          <meta property="og:type" content="website" />
          <meta property="og:title" content="Bigstep Technologies" />
          <meta property="og:description" content="Generated by create next app" />
          <meta property="og:image" content="URL_to_your_image.jpg" />
          <meta property="og:url" content="https://www.yourwebsite.com" />

          {/* Twitter Card Meta Tags */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="Bigstep Technologies" />
          <meta name="twitter:description" content="Generated by create next app" />
          <meta name="twitter:image" content="URL_to_your_image.jpg" />
        </Head>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
